# Generated by Django 4.1 on 2023-03-22 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clgstore", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="college",
            name="icon",
            field=models.ImageField(default=1, upload_to="photo"),
            preserve_default=False,
        ),
    ]
